[package]
name = "fraud-guard"
version = "0.1.0"
edition = "2024"
authors = ["Ruslan Filimonov"]
license = "BSD-3-Clause"
description = "A rule-based fraud detection engine"
repository = "https://github.com/ruslan-codebase/fraud-guard"
readme = "README.md"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
