[package]
name = "fraud-guard-domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Domain types and traits for fraud-guard"

[dependencies]
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
chrono = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
